In [ ]:
import numpy as np

In [ ]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [ ]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  1
Shape of t:  (7,)


In [ ]:
print('t[0] t[1] t[-1]', t[0], t[1], t[-1])

t[0] t[1] t[-1] 0.0 1.0 6.0


In [ ]:
print('t[2:5] t[4:-1] = ', t[2:5], t[4:-1])

t[2:5] t[4:-1] =  [2. 3. 4.] [4. 5.]


In [ ]:
print('t[:2] t[3:] = ', t[:2], t[3:])

t[:2] t[3:] =  [0. 1.] [3. 4. 5. 6.]


In [ ]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
Rank of t:  2
Shape of t:  (4, 3)


#PyTorch Tensor Allocation

In [1]:
import torch

In [3]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)
print(t.dim())
print(t.shape)
print(t.size())

tensor([0., 1., 2., 3., 4., 5., 6.])
1
torch.Size([7])
torch.Size([7])


In [4]:
print(t[0], [1], [-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

tensor(0.) [1] [-1]
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [8]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                       ])
print(t)
print(t.dim())
print(t.size())

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
2
torch.Size([4, 3])


In [10]:
print(t[:, 1])
print(t[:, 1].size())

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [11]:
print(t[:, :-1])

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


Broadcasting
이런 기능은 없는게 낫지 않을까? 많이 했갈릴 것 같다.

In [12]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [13]:
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3])
print(m1 + m2)

tensor([[4., 5.]])


In [14]:
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


Matrix Multiplication VS Multiplication

In [15]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of m1 : ', m1.shape)
print('Shape of m2 : ', m2.shape)
print(m1.matmul(m2))

Shape of m1 :  torch.Size([2, 2])
Shape of m2 :  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [16]:
print(m1*m2)   #매트랩에서는 이게 도트 프로덕트다.
print(m1.mul(m2))

tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


Mean

In [18]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [22]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))  #인자로 넘긴 차원을 지우는거임. 남기는거 아님.
print(t.mean(dim=-1)) #이것도 좀 햇갈리네

tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [23]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor([[1., 2.],
        [3., 4.]])
tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


Max and ArgMax

In [31]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.max())
print(t.max(dim=0))

print('\n\nmax: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

print()
print(t.max(dim=1))
print(t.max(dim=-1))

tensor([[1., 2.],
        [3., 4.]])
tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


max:  tensor([3., 4.])
Argmax:  tensor([1, 1])

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


In [36]:
import numpy as np
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11 ]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [38]:
print(ft.view([-1, 3]))      # -1은 미정을 뜻함. (?, 3)의 크기로 변경하는것
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [39]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


Squeeze