In [2]:
import numpy as np

In [3]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [4]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  1
Shape of t:  (7,)


In [5]:
print('t[0] t[1] t[-1]', t[0], t[1], t[-1])

t[0] t[1] t[-1] 0.0 1.0 6.0


In [6]:
print('t[2:5] t[4:-1] = ', t[2:5], t[4:-1])

t[2:5] t[4:-1] =  [2. 3. 4.] [4. 5.]


In [7]:
print('t[:2] t[3:] = ', t[:2], t[3:])

t[:2] t[3:] =  [0. 1.] [3. 4. 5. 6.]


In [8]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
Rank of t:  2
Shape of t:  (4, 3)


#PyTorch Tensor Allocation

In [9]:
import torch

In [10]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)
print(t.dim())
print(t.shape)
print(t.size())

tensor([0., 1., 2., 3., 4., 5., 6.])
1
torch.Size([7])
torch.Size([7])


In [11]:
print(t[0], [1], [-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

tensor(0.) [1] [-1]
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [12]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                       ])
print(t)
print(t.dim())
print(t.size())

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
2
torch.Size([4, 3])


In [13]:
print(t[:, 1])
print(t[:, 1].size())

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [14]:
print(t[:, :-1])

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


Broadcasting
이런 기능은 없는게 낫지 않을까? 많이 했갈릴 것 같다.

In [15]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [16]:
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3])
print(m1 + m2)

tensor([[4., 5.]])


In [17]:
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


Matrix Multiplication VS Multiplication

In [18]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of m1 : ', m1.shape)
print('Shape of m2 : ', m2.shape)
print(m1.matmul(m2))

Shape of m1 :  torch.Size([2, 2])
Shape of m2 :  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [19]:
print(m1*m2)   #매트랩에서는 이게 도트 프로덕트다.
print(m1.mul(m2))

tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


Mean

In [20]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [21]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))  #인자로 넘긴 차원을 지우는거임. 남기는거 아님.
print(t.mean(dim=-1)) #이것도 좀 햇갈리네

tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [22]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor([[1., 2.],
        [3., 4.]])
tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


Max and ArgMax

In [23]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.max())
print(t.max(dim=0))

print('\n\nmax: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

print()
print(t.max(dim=1))
print(t.max(dim=-1))

tensor([[1., 2.],
        [3., 4.]])
tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


max:  tensor([3., 4.])
Argmax:  tensor([1, 1])

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


In [24]:
import numpy as np
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11 ]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [25]:
print(ft.view([-1, 3]))      # -1은 미정을 뜻함. (?, 3)의 크기로 변경하는것
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [26]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


Squeeze<br>
설명에는 1인 차원을 제거한다고 되어 있는데... 차원이 1인경우 한 차원 내린다고 보는게 맞는듯.

In [28]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)
print()
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])

tensor([0., 1., 2.])
torch.Size([3])


Unsqueeze : 반대

In [35]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)
print()
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)
print()
print(ft.view(1, -1))
print(ft.view(1, -1).shape)
print()
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)
print()
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

torch.Size([3])

tensor([[0., 1., 2.]])
torch.Size([1, 3])

tensor([[0., 1., 2.]])
torch.Size([1, 3])

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


Type Casting

In [38]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)
print(lt.float())

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])


In [40]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1], dtype=torch.uint8)
tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


Concatenate

In [42]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

print(torch.cat([x, y], dim=0))
print(torch.cat([x, y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


Stacking

In [44]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

print(torch.stack([x, y, z]))
print(torch.stack([x, y, z], dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


ones_like and zeros_like

In [47]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[0., 1., 2.],
        [2., 1., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In-place Operation

In [48]:
x = torch.FloatTensor([[1, 2], [3, 4]])

print(x.mul(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [49]:
print(x.mul_(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
