### Simple Linear Regression

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1)

In [5]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

model = nn.Linear(1, 1)

print(list(model.parameters()))

[Parameter containing:
tensor([[-0.1939]], requires_grad=True), Parameter containing:
tensor([0.4694], requires_grad=True)]


In [ ]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

nb_epochs = 2000
for epoch in range(nb_epochs + 1):
  prediction = model(x_train)
  cost = F.mse_loss(prediction, y_train)
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
    print('Epoch {:4d}/{} Cost:{:.6f}'.format(
        epoch, nb_epochs, cost.item()
    ))

In [8]:
new_var = torch.FloatTensor([[4.0]])
pred_y = model(new_var)
print("훈련 후 입력이 4일때의 예측값 : ", pred_y)
print(list(model.parameters()))

훈련 후 입력이 4일때의 예측값 :  tensor([[7.9926]], grad_fn=<AddmmBackward0>)
[Parameter containing:
tensor([[1.9957]], requires_grad=True), Parameter containing:
tensor([0.0097], requires_grad=True)]


### Multivariable Linear Regression

In [9]:
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1)

In [10]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

model = nn.Linear(3, 1)
print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119]], requires_grad=True), Parameter containing:
tensor([0.2710], requires_grad=True)]


In [ ]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

nb_epochs = 2000
for epoch in range(nb_epochs + 1):
  prediction = model(x_train)
  cost = F.mse_loss(prediction, y_train)
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
    print('Epoch {:4d}/{} Cost:{:.6f}'.format(
        epoch, nb_epochs, cost.item()
    ))

In [14]:
new_var = torch.FloatTensor([[73, 80, 75]])

pred_y = model(new_var)
print("훈련 후 입력이 73, 80, 75일때 예측값 :", pred_y)

print(list(model.parameters()))

훈련 후 입력이 73, 80, 75일때 예측값 : tensor([[151.2305]], grad_fn=<AddmmBackward0>)
[Parameter containing:
tensor([[0.9778, 0.4539, 0.5768]], requires_grad=True), Parameter containing:
tensor([0.2802], requires_grad=True)]


### **IMPORTANT** Implementing a Model in a Class


##### Simple Linear Regression

In [17]:
#model = nn.Linear(1, 1)

class LinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(1, 1)

  def forward(self, x):
    return self.linear(x)

model = LinearRegressionModel()

##### Multivariable Linear Regresiion

In [21]:
#model = nn.Linear(1, 1)

class MultivariateLinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(3, 1)

  def forward(self, x):
    self.linear(x)

model = MultivariateLinearRegressionModel()

### Implementing Simple Linear Regression in a Class

In [24]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

class LinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(1, 1)

  def forward(self, x):
    return self.linear(x)

model = LinearRegressionModel()

In [28]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

nb_epochs = 2000
for epoch in range(nb_epochs + 1):
  prediction = model(x_train)
  cost = F.mse_loss(prediction, y_train)
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
    print('Epoch {:4d}/{} Cost:{:.6f}'.format(
        epoch, nb_epochs, cost.item()
    ))

Epoch    0/2000 Cost:0.000000
Epoch  100/2000 Cost:0.000000
Epoch  200/2000 Cost:0.000000
Epoch  300/2000 Cost:0.000000
Epoch  400/2000 Cost:0.000000
Epoch  500/2000 Cost:0.000000
Epoch  600/2000 Cost:0.000000
Epoch  700/2000 Cost:0.000000
Epoch  800/2000 Cost:0.000000
Epoch  900/2000 Cost:0.000000
Epoch 1000/2000 Cost:0.000000
Epoch 1100/2000 Cost:0.000000
Epoch 1200/2000 Cost:0.000000
Epoch 1300/2000 Cost:0.000000
Epoch 1400/2000 Cost:0.000000
Epoch 1500/2000 Cost:0.000000
Epoch 1600/2000 Cost:0.000000
Epoch 1700/2000 Cost:0.000000
Epoch 1800/2000 Cost:0.000000
Epoch 1900/2000 Cost:0.000000
Epoch 2000/2000 Cost:0.000000


### Implementing Multivariable Linear Regression in a Class

In [34]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

class MultivariateLinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(3, 1)

  def forward(self, x):
    return self.linear(x)

model = MultivariateLinearRegressionModel()

optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

nb_epochs = 2000
for epoch in range(nb_epochs + 1):
  prediction = model(x_train)
  cost = F.mse_loss(prediction, y_train)
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
    print('Epoch {:4d}/{} Cost:{:.6f}'.format(
        epoch, nb_epochs, cost.item()
    ))

Epoch    0/2000 Cost:25809.587891
Epoch  100/2000 Cost:0.298808
Epoch  200/2000 Cost:0.292559
Epoch  300/2000 Cost:0.286632
Epoch  400/2000 Cost:0.281008
Epoch  500/2000 Cost:0.275684
Epoch  600/2000 Cost:0.270632
Epoch  700/2000 Cost:0.265832
Epoch  800/2000 Cost:0.261289
Epoch  900/2000 Cost:0.256981
Epoch 1000/2000 Cost:0.252894
Epoch 1100/2000 Cost:0.249015
Epoch 1200/2000 Cost:0.245331
Epoch 1300/2000 Cost:0.241845
Epoch 1400/2000 Cost:0.238542
Epoch 1500/2000 Cost:0.235392
Epoch 1600/2000 Cost:0.232420
Epoch 1700/2000 Cost:0.229590
Epoch 1800/2000 Cost:0.226897
Epoch 1900/2000 Cost:0.224347
Epoch 2000/2000 Cost:0.221932
